site_name: KontrolSystem 2
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - awesome-pages
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition